Validating modified rul files Yaml Schema Validator and Linting

diff --git a/.forgejo/workflows/workflow_yamllint.yml b/.forgejo/workflows/workflow_yamllint.yml
--- a/.forgejo/workflows/workflow_yamllint.yml
+++ b/.forgejo/workflows/workflow_yamllint.yml
@@ -23,9 +23,27 @@ jobs:
         run: |
           pip3 install yamllint
 
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v44
+
       # Step 3: Run yamllint on all YAML files
       - name: Lint YAML files
         run: |
           echo "Start Linting"
-          yamllint --no-warnings -c ./.yamllint.yml .
-          echo "Completed Linting"
+          RETURN_CODE=0
+          for file in ${{ steps.changed-files.outputs.all_changed_files }};
+          do
+            echo "Linting $file"
+            yamllint --no-warnings -c ./.yamllint.yml $file
+            if [ $? -ne 0 ]; then  # check if return code fails at least once in the for loop
+              RETURN_CODE=1
+            fi
+          done
+          if [ $RETURN_CODE -ne 0 ]; then
+            echo "Linting failed"
+            false  # fail workflow step
+          else
+            echo "Linting done"
+            true
+          fi
